name: Ruff Linting

on:
  push:
    paths:
      - "**/*.py"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v2
        with:
          version: "0.8.x"
